import {RECORDED_REPORTS,SAMPLE_FILES} from './csAudioRecordings.js';
import {synthesizeShot,SHOT_VARIANTS} from './csAudioSynthesis.js';
export class GameAudio {
  constructor(){this.ctx=null;this.enabled=true;this.master=null;this.noise=null;this.reports=new Map();this.shotCount=0;this.samples=new Map();this.rawSamples=new Map();this.decoding=new Set();this.loadTask=null;this.lastLoad=-Infinity;}
  init(){try{if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.31;const limiter=this.ctx.createDynamicsCompressor();limiter.threshold.value=-5;limiter.knee.value=3;limiter.ratio.value=12;limiter.attack.value=.001;limiter.release.value=.055;this.master.connect(limiter);limiter.connect(this.ctx.destination);this.noise=this.ctx.createBuffer(1,Math.ceil(this.ctx.sampleRate*.6),this.ctx.sampleRate);const a=this.noise.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;for(const id of ['ak47','deagle','awp','glock','usp','m4a1'])this.report(id,['usp','m4a1'].includes(id),0);}this.preload();for(const [file,data] of this.rawSamples)this.decode(file,data);if(this.ctx.state==='suspended')this.ctx.resume();}catch{}}
  preload(){
    if(this.loadTask||this.rawSamples.size===SAMPLE_FILES.length||Date.now()-this.lastLoad<15000)return this.loadTask;
    this.lastLoad=Date.now();const pending=SAMPLE_FILES.filter(file=>!this.rawSamples.has(file));
    const worker=async()=>{while(pending.length){const file=pending.shift();try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let data;try{const response=await fetch('/cs/assets/audio/'+file,{signal:controller.signal});if(!response.ok)throw new Error('Audio asset unavailable');data=await response.arrayBuffer();}finally{clearTimeout(timer);}this.rawSamples.set(file,data);this.decode(file,data);}catch{/* Keep the immediate local fallback; retry on a later user gesture. */}}};
    this.loadTask=Promise.all(Array.from({length:4},worker)).finally(()=>{this.loadTask=null;});return this.loadTask;
  }
  decode(file,data){if(!this.ctx||this.samples.has(file)||this.decoding.has(file))return;this.decoding.add(file);try{this.ctx.decodeAudioData(data.slice(0)).then(buffer=>{this.samples.set(file,buffer);this.rawSamples.set(file,null);}).catch(()=>{this.rawSamples.delete(file);}).finally(()=>this.decoding.delete(file));}catch{this.decoding.delete(file);this.rawSamples.delete(file);}}
  report(id,suppressed,variant){const choices=RECORDED_REPORTS[id]?.[suppressed?'suppressed':'normal']||RECORDED_REPORTS[id]?.normal;if(choices?.length){const preferred=choices[variant%choices.length],recorded=this.samples.get(preferred)||choices.map(file=>this.samples.get(file)).find(Boolean);if(recorded)return recorded;}const key=id+':'+suppressed+':'+variant;if(!this.reports.has(key)){const pcm=synthesizeShot(id,this.ctx.sampleRate,variant,suppressed),buffer=this.ctx.createBuffer(2,pcm.left.length,pcm.sampleRate);buffer.copyToChannel(pcm.left,0);buffer.copyToChannel(pcm.right,1);this.reports.set(key,buffer);}return this.reports.get(key);}
  route(node,pan=0){if(this.ctx.createStereoPanner){const p=this.ctx.createStereoPanner();p.pan.value=Math.max(-1,Math.min(1,pan));node.connect(p);p.connect(this.master);return p;}node.connect(this.master);return null;}
  tone(freq,dur=.12,vol=.3,type='sine',end=0){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+dur);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur);}
  burst(dur,vol,low=1000,pan=0){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime,s=this.ctx.createBufferSource(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();s.buffer=this.noise;f.type='lowpass';f.frequency.value=low;g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);s.connect(f);f.connect(g);if(this.ctx.createStereoPanner){const p=this.ctx.createStereoPanner();p.pan.value=Math.max(-1,Math.min(1,pan));g.connect(p);p.connect(this.master);}else g.connect(this.master);s.start(t);s.stop(t+dur);}
  shot(id,volume=1,pan=0,suppressed,distance=0){
    if(!this.enabled||!this.ctx)return;if(id==='knife'){this.burst(.12,.17*volume,3200,pan);return;}
    const quiet=suppressed??['m4a1','usp','mp5'].includes(id),variant=this.shotCount++%SHOT_VARIANTS,s=this.ctx.createBufferSource(),gain=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();s.buffer=this.report(id,quiet,variant);s.playbackRate.value=1+(Math.random()-.5)*.013;filter.type='lowpass';filter.frequency.value=distance?Math.max(1600,15500*Math.exp(-distance/40)):19000;filter.Q.value=.5;gain.gain.value=volume*(id==='awp'?1.12:id==='deagle'?1.02:id==='mp5'?1.10:.94);s.connect(filter);filter.connect(gain);const panNode=this.route(gain,pan);s.start();s.onended=()=>{s.disconnect();filter.disconnect();gain.disconnect();panNode?.disconnect();};
  }
  step(){this.burst(.085,.12,650);}
  reload(){this.mechanic('mag-in');}
  mechanic(kind){const cues={'cloth':[.075,.07,1500,0],'mag-out':[.060,.14,3400,610],'mag-in':[.055,.21,4700,830],'bolt-lift':[.035,.10,4700,1400],'bolt-open':[.095,.16,5300,980],'bolt-close':[.055,.23,6500,1600],'bolt-lock':[.029,.13,4900,1300],'shell':[.048,.12,3900,720],'cover':[.075,.16,2600,520]};const [duration,volume,low,freq]=cues[kind]||cues.cloth;this.burst(duration,volume,low);if(freq)this.tone(freq,.014,volume*.10,'triangle',freq*.68);}
  hit(head=false){this.tone(head?1550:980,.06,.25,'sine');}
  round(win){this.tone(win?523:330,.22,.3);setTimeout(()=>this.tone(win?659:277,.25,.3),160);setTimeout(()=>this.tone(win?784:220,.4,.3),330);}
}
